#!/bin/sh
set -e

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
VERSIONS_DIR="$ROOT_DIR/app/modules/share/infrastructure/db/alembic/versions"

echo "[parse-reset] Docker compose down -v"
docker compose down -v

echo "[parse-reset] Cleaning autogenerated alembic migrations"
if [ -d "$VERSIONS_DIR" ]; then
  for migration in "$VERSIONS_DIR"/*.py; do
    [ -f "$migration" ] || continue
    rm -f "$migration"
  done
fi

echo "[parse-reset] Starting clean stack"
docker compose up --build
