"""
Configuración de leyes para búsqueda legal.
Edita este archivo para agregar/modificar leyes y keywords.
"""

LAW_MAPPINGS = {
    # Códigos principales
    "CODIGO CIVIL FEDERAL": "CÓDIGO CIVIL FEDERAL",
    "CIVIL FEDERAL": "CÓDIGO CIVIL FEDERAL",
    "CCF": "CÓDIGO CIVIL FEDERAL",
    "CODIGO DE COMERCIO": "CÓDIGO DE COMERCIO",
    "COMERCIO": "CÓDIGO DE COMERCIO",
    "CODIGO PENAL": "CÓDIGO PENAL FEDERAL",
    "PENAL FEDERAL": "CÓDIGO PENAL FEDERAL",
    "CODIGO FEDERAL DE PROCEDIMIENTOS CIVILES": "CÓDIGO FEDERAL DE PROCEDIMIENTOS CIVILES",
    "CFPC": "CÓDIGO FEDERAL DE PROCEDIMIENTOS CIVILES",
    "CODIGO DE JUSTICIA MILITAR": "CÓDIGO DE JUSTICIA MILITAR",
    "JUSTICIA MILITAR": "CÓDIGO DE JUSTICIA MILITAR",
    "CODIGO FISCAL DE LA FEDERACION": "CÓDIGO FISCAL DE LA FEDERACIÓN",
    "CFF": "CÓDIGO FISCAL DE LA FEDERACIÓN",
    "CODIGO NACIONAL DE PROCEDIMIENTOS PENALES": "CÓDIGO NACIONAL DE PROCEDIMIENTOS PENALES",
    "CNPP": "CÓDIGO NACIONAL DE PROCEDIMIENTOS PENALES",
    "CODIGO ELECTORAL": "Código Electoral Federal",
    # Leyes constitucionales y de justicia
    "LEY DE AMPARO": "Ley de Amparo, Reglamentaria de los Artículos 103 y 107 de la Constitución Política de los Estados Unidos Mexicanos",
    "AMPARO": "Ley de Amparo, Reglamentaria de los Artículos 103 y 107 de la Constitución Política de los Estados Unidos Mexicanos",
    "LEY ORGANICA DEL PODER JUDICIAL": "Ley Orgánica del Poder Judicial de la Federación",
    "ORGANICA DEL PODER JUDICIAL": "Ley Orgánica del Poder Judicial de la Federación",
    "LOPJF": "Ley Orgánica del Poder Judicial de la Federación",
    "PODER JUDICIAL": "Ley Orgánica del Poder Judicial de la Federación",
    "LEY ORGANICA DE LA ADMINISTRACION PUBLICA": "Ley Orgánica de la Administración Pública Federal",
    "LOAPF": "Ley Orgánica de la Administración Pública Federal",
    "ADMINISTRACION PUBLICA": "Ley Orgánica de la Administración Pública Federal",
    # Leyes laborales
    "LEY FEDERAL DEL TRABAJO": "Ley Federal del Trabajo",
    "LFT": "Ley Federal del Trabajo",
    "TRABAJO": "Ley Federal del Trabajo",
    "TRABAJADOR": "Ley Federal del Trabajo",
    "TRABAJADORES": "Ley Federal del Trabajo",
    "PATRON": "Ley Federal del Trabajo",
    "SALARIO": "Ley Federal del Trabajo",
    "INFONAVIT": "Ley del Instituto del Fondo Nacional de la Vivienda para los Trabajadores",
    "FONACOT": "Ley del Instituto Nacional del Fondo Profesional para los Trabajadores",
    "IMSS": "Ley del Seguro General",
    "ISSSTE": "Ley del Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado",
    "SEGURIDAD SOCIAL": "Ley del Seguro General",
    # Leyes de salud y educativo
    "LEY GENERAL DE SALUD": "Ley General de Salud",
    "LGS": "Ley General de Salud",
    "SALUD": "Ley General de Salud",
    "LEY DE SALUD": "Ley General de Salud",
    "ESTUPEFACIENTES": "Ley General de Salud",
    "NARCOTICOS": "Ley General de Salud",
    "PSICOTROPICOS": "Ley General de Salud",
    "LEY GENERAL DE EDUCACION": "Ley General de Educación",
    "LGE": "Ley General de Educación",
    "EDUCACION": "Ley General de Educación",
    "EDUCATIVA": "Ley General de Educación",
    "SEP": "Ley General de Educación",
    # Leyes mercantiles y financieras
    "LEY DEL MERCADO DE VALORES": "Ley del Mercado de Valores",
    "LMV": "Ley del Mercado de Valores",
    "MERCADO DE VALORES": "Ley del Mercado de Valores",
    "VALORES": "Ley del Mercado de Valores",
    "LEY DE INSTITUCIONES DE CREDITO": "Ley de Instituciones de Crédito",
    "LIC": "Ley de Instituciones de Crédito",
    "CREDITO": "Ley de Instituciones de Crédito",
    "BANCARIA": "Ley de Instituciones de Crédito",
    "BANCARIO": "Ley de Instituciones de Crédito",
    "CONDUSEF": "Ley de Protección y Defensa al Usuario de Servicios Financieros",
    "USUARIO FINANCIERO": "Ley de Protección y Defensa al Usuario de Servicios Financieros",
    # Propiedad intelectual
    "LEY FEDERAL DEL DERECHO DE AUTOR": "Ley Federal del Derecho de Autor",
    "DERECHO DE AUTOR": "Ley Federal del Derecho de Autor",
    "COPYRIGHT": "Ley Federal del Derecho de Autor",
    "PROPIEDAD INDUSTRIAL": "Ley de la Propiedad Industrial",
    "LPI": "Ley de la Propiedad Industrial",
    "MARCAS": "Ley de la Propiedad Industrial",
    "PATENTES": "Ley de la Propiedad Industrial",
    # Protección de datos
    "LEY FEDERAL DE PROTECCION DE DATOS PERSONALES": "Ley Federal de Protección de Datos Personales en Posesión de los Particulares",
    "LFPDPPP": "Ley Federal de Protección de Datos Personales en Posesión de los Particulares",
    "PROTECCION DE DATOS": "Ley Federal de Protección de Datos Personales en Posesión de los Particulares",
    "DATOS PERSONALES": "Ley Federal de Protección de Datos Personales en Posesión de los Particulares",
    "PRIVACIDAD": "Ley Federal de Protección de Datos Personales en Posesión de los Particulares",
    # Ambiental y recursos naturales
    "LEY DE AGUAS NACIONALES": "Ley de Aguas Nacionales",
    "AGUAS NACIONALES": "Ley de Aguas Nacionales",
    "LEY GENERAL DEL EQUILIBRIO ECOLOGICO": "Ley General del Equilibrio Ecológico y la Protección al Ambiente",
    "LGEEPA": "Ley General del Equilibrio Ecológico y la Protección al Ambiente",
    "EQUILIBRIO ECOLOGICO": "Ley General del Equilibrio Ecológico y la Protección al Ambiente",
    "MEDIO AMBIENTE": "Ley General del Equilibrio Ecológico y la Protección al Ambiente",
    "AMBIENTAL": "Ley General del Equilibrio Ecológico y la Protección al Ambiente",
    "ECOLOGIA": "Ley General del Equilibrio Ecológico y la Protección al Ambiente",
    "RESIDUOS": "Ley General para la Prevención y Gestión Integral de los Residuos",
    "RESIDUOS PELIGROSOS": "Ley General para la Prevención y Gestión Integral de los Residuos",
    "PREVENCION DE RESIDUOS": "Ley General para la Prevención y Gestión Integral de los Residuos",
    "BIOSEGURIDAD": "Ley de Bioseguridad de Organismos Genéticamente Modificados",
    "OGM": "Ley de Bioseguridad de Organismos Genéticamente Modificados",
    # Extinción de dominio
    "LEY NACIONAL DE EXTINCION DE DOMINIO": "Ley Nacional de Extinción de Dominio",
    "EXTINCION DE DOMINIO": "Ley Nacional de Extinción de Dominio",
    "DOMINIO": "Ley Nacional de Extinción de Dominio",
    # Fiscales y tributarias
    "LEY DEL IMPUESTO SOBRE LA RENTA": "Ley del Impuesto sobre la Renta",
    "LISR": "Ley del Impuesto sobre la Renta",
    "ISR": "Ley del Impuesto sobre la Renta",
    "RENTA": "Ley del Impuesto sobre la Renta",
    "LEY DEL IMPUESTO AL VALOR AGREGADO": "Ley del Impuesto al Valor Agregado",
    "LIVA": "Ley del Impuesto al Valor Agregado",
    "IVA": "Ley del Impuesto al Valor Agregado",
    "LEY DEL IMPUESTO ESPECIAL": "Ley del Impuesto Especial sobre Producción y Servicios",
    "IEPS": "Ley del Impuesto Especial sobre Producción y Servicios",
    "LEY FEDERAL DE DERECHOS": "Ley Federal de Derechos",
    "DERECHOS": "Ley Federal de Derechos",
    "LEY DE INGRESOS SOBRE HIDROCARBUROS": "Ley de Ingresos sobre Hidrocarburos",
    "HIDROCARBUROS": "Ley de Ingresos sobre Hidrocarburos",
    "PETROLEO": "Ley de Ingresos sobre Hidrocarburos",
    "GAS": "Ley de Ingresos sobre Hidrocarburos",
    "LEY DE INGRESOS DE LA FEDERACION": "Ley de Ingresos de la Federación",
    "LEY ADUANERA": "Ley Aduanera",
    "ADUANAS": "Ley Aduanera",
    "ADUANERA": "Ley Aduanera",
    # Agrarias
    "LEY AGRARIA": "Ley Agraria",
    "AGRARIA": "Ley Agraria",
    "EJIDO": "Ley Agraria",
    "COMUNIDAD": "Ley Agraria",
    "LEY DE PLANEACION AGRARIA": "Ley de Planeación Agraria",
    "PLANEACION AGRARIA": "Ley de Planeación Agraria",
    "LEY DE REFORMA AGRARIA": "Ley de Reforma Agraria",
    "REFORMA AGRARIA": "Ley de Reforma Agraria",
    # Migratorias
    "LEY DE MIGRACION": "Ley de Migración",
    "MIGRACION": "Ley de Migración",
    "MIGRATORIA": "Ley de Migración",
    "MIGRATORIO": "Ley de Migración",
    "INM": "Ley de Migración",
    "EXTRANJEROS": "Ley de Migración",
    "EXTRANJERO": "Ley de Migración",
    "VISAS": "Ley de Migración",
    # Energía
    "LEY DE LA INDUSTRIA ELECTRICA": "Ley de la Industria Eléctrica",
    "INDUSTRIA ELECTRICA": "Ley de la Industria Eléctrica",
    "ELECTRICA": "Ley de la Industria Eléctrica",
    "ENERGIA": "Ley de la Industria Eléctrica",
    "LEY DE HIDROCARBUROS": "Ley de Hidrocarburos",
    "LEY MINERA": "Ley Minera",
    "MINERA": "Ley Minera",
    "MINERIA": "Ley Minera",
    # Transporte
    "LEY DE AVIACION CIVIL": "Ley de Aviación Civil",
    "AVIACION CIVIL": "Ley de Aviación Civil",
    "AVIACION": "Ley de Aviación Civil",
    "AERONAUTICA": "Ley de Aviación Civil",
    "LEY DE CAMINOS": "Ley de Caminos",
    "CAMINOS": "Ley de Caminos",
    "LEY DE FERROCARRILES": "Ley de Ferrocarriles",
    "FERROCARRILES": "Ley de Ferrocarriles",
    "FERROCARRIL": "Ley de Ferrocarriles",
    "LEY DE NAVEGACION": "Ley de Navegación y Transporte Marítimo",
    "NAVEGACION": "Ley de Navegación y Transporte Marítimo",
    "MARITIMA": "Ley de Navegación y Transporte Marítimo",
    "MARITIMO": "Ley de Navegación y Transporte Marítimo",
    "TRANSPORTE MARITIMO": "Ley de Navegación y Transporte Marítimo",
    "LEY DE TRANSITO": "Ley de Tránsito y Transporte terrestre",
    "TRANSITO": "Ley de Tránsito y Transporte terrestre",
    "TRANSPORTE TERRESTRE": "Ley de Tránsito y Transporte terrestre",
    # Comunicaciones y obras
    "LEY DE OBRAS PUBLICAS": "Ley de Obras Públicas y Servicios Relacionados con las Mismas",
    "LOP": "Ley de Obras Públicas y Servicios Relacionados con las Mismas",
    "OBRAS PUBLICAS": "Ley de Obras Públicas y Servicios Relacionados con las Mismas",
    "CONTRATISTA": "Ley de Obras Públicas y Servicios Relacionados con las Mismas",
    "LEY DE ADQUISICIONES": "Ley de Adquisiciones, Arrendamientos y Servicios del Sector Público",
    "LAASSP": "Ley de Adquisiciones, Arrendamientos y Servicios del Sector Público",
    "ADQUISICIONES": "Ley de Adquisiciones, Arrendamientos y Servicios del Sector Público",
    "ARRENDAMIENTOS": "Ley de Adquisiciones, Arrendamientos y Servicios del Sector Público",
    # Pesca y agricultura
    "LEY DE PESCA": "Ley General de Pesca y Acuacultura Sustentables",
    "PESCA": "Ley General de Pesca y Acuacultura Sustentables",
    "ACUACULTURA": "Ley General de Pesca y Acuacultura Sustentables",
    "LEY FEDERAL DE SANIDAD VEGETAL": "Ley Federal de Sanidad Vegetal",
    "SANIDAD VEGETAL": "Ley Federal de Sanidad Vegetal",
    "LEY FEDERAL DE SANIDAD ANIMAL": "Ley Federal de Sanidad Animal",
    "SANIDAD ANIMAL": "Ley Federal de Sanidad Animal",
    "LEY DE DESARROLLO RURAL": "Ley de Desarrollo Rural Sustentable",
    "DESARROLLO RURAL": "Ley de Desarrollo Rural Sustentable",
    "RURAL": "Ley de Desarrollo Rural Sustentable",
    "AGRICOLA": "Ley de Desarrollo Rural Sustentable",
    # Vivienda y desarrollo urbano
    "LEY DE VIVIENDA": "Ley de Vivienda",
    "VIVIENDA": "Ley de Vivienda",
    "HIPOTECA": "Ley de Vivienda",
    "HIPOTECARIO": "Ley de Vivienda",
    "LEY DE ORDENAMIENTO TERRITORIAL": "Ley de Ordenamiento Territorial y Desarrollo Urbano",
    "ORDENAMIENTO TERRITORIAL": "Ley de Ordenamiento Territorial y Desarrollo Urbano",
    "DESARROLLO URBANO": "Ley de Ordenamiento Territorial y Desarrollo Urbano",
    "URBANO": "Ley de Ordenamiento Territorial y Desarrollo Urbano",
    "URBANA": "Ley de Ordenamiento Territorial y Desarrollo Urbano",
    # Turismo
    "LEY DE TURISMO": "Ley General de Turismo",
    "TURISMO": "Ley General de Turismo",
    "TURISTICO": "Ley General de Turismo",
    # Desarrollo social
    "LEY DE DESARROLLO SOCIAL": "Ley General de Desarrollo Social",
    "DESARROLLO SOCIAL": "Ley General de Desarrollo Social",
    "POBREZA": "Ley General de Desarrollo Social",
    "MARGINACION": "Ley General de Desarrollo Social",
    "CONEVAL": "Ley General de Desarrollo Social",
    "CONSEJO NACIONAL DE EVALUACION": "Ley General de Desarrollo Social",
    # Transparencia y anticorrupción
    "LEY DE TRANSPARENCIA": "Ley General de Transparencia y Acceso a la Información Pública",
    "TRANSPARENCIA": "Ley General de Transparencia y Acceso a la Información Pública",
    "ACCESO A LA INFORMACION": "Ley General de Transparencia y Acceso a la Información Pública",
    "INAI": "Ley General de Transparencia y Acceso a la Información Pública",
    "IFAI": "Ley General de Transparencia y Acceso a la Información Pública",
    "LEY ANTICORRUPCION": "Ley General de Responsabilidades Administrativas",
    "ANTICORRUPCION": "Ley General de Responsabilidades Administrativas",
    "SISTEMA NACIONAL ANTICORRUPCION": "Ley General de Responsabilidades Administrativas",
    "SNA": "Ley General de Responsabilidades Administrativas",
    "LEY GENERAL DE RESPONSABILIDADES ADMINISTRATIVAS": "Ley General de Responsabilidades Administrativas",
    "RESPONSABILIDADES ADMINISTRATIVAS": "Ley General de Responsabilidades Administrativas",
    # Protección civil
    "LEY DE PROTECCION CIVIL": "Ley General de Protección Civil",
    "PROTECCION CIVIL": "Ley General de Protección Civil",
    "EMERGENCIA": "Ley General de Protección Civil",
    "DESASTRE": "Ley General de Protección Civil",
    # Niños, niñas y adolescentes
    "LEY DE LOS DERECHOS DE NINAS": "Ley General de los Derechos de Niñas, Niños y Adolescentes",
    "DERECHOS DE NINAS": "Ley General de los Derechos de Niñas, Niños y Adolescentes",
    "DERECHOS DE NINOS": "Ley General de los Derechos de Niñas, Niños y Adolescentes",
    "INFANCIA": "Ley General de los Derechos de Niñas, Niños y Adolescentes",
    "MENORES": "Ley General de los Derechos de Niñas, Niños y Adolescentes",
    "NIÑOS": "Ley General de los Derechos de Niñas, Niños y Adolescentes",
    "NNA": "Ley General de los Derechos de Niñas, Niños y Adolescentes",
    "LEY DE LA JUVENTUD": "Ley Federal de los Derechos de la Juventud",
    "JUVENTUD": "Ley Federal de los Derechos de la Juventud",
    "JOVEN": "Ley Federal de los Derechos de la Juventud",
    "JOVENES": "Ley Federal de los Derechos de la Juventud",
    # Igualdad y no discriminación
    "LEY DE IGUALDAD": "Ley General para la Igualdad entre Mujeres y Hombres",
    "IGUALDAD": "Ley General para la Igualdad entre Mujeres y Hombres",
    "GENERO": "Ley General para la Igualdad entre Mujeres y Hombres",
    "VIOLENCIA DE GENERO": "Ley General para la Igualdad entre Mujeres y Hombres",
    "DISCRIMINACION": "Ley Federal para Prevenir y Eliminar la Discriminación",
    # Adultos mayores
    "LEY DE LOS ADULTOS MAYORES": "Ley de los Derechos de las Personas Adultas Mayores",
    "ADULTOS MAYORES": "Ley de los Derechos de las Personas Adultas Mayores",
    "PERSONAS ADULTAS MAYORES": "Ley de los Derechos de las Personas Adultas Mayores",
    "ANCIANOS": "Ley de los Derechos de las Personas Adultas Mayores",
    "TERCERA EDAD": "Ley de los Derechos de las Personas Adultas Mayores",
    # Personas con discapacidad
    "LEY DE PERSONAS CON DISCAPACIDAD": "Ley General para la Inclusión de las Personas con Discapacidad",
    "DISCAPACIDAD": "Ley General para la Inclusión de las Personas con Discapacidad",
    "DISCAPACITADOS": "Ley General para la Inclusión de las Personas con Discapacidad",
    "INCLUSION": "Ley General para la Inclusión de las Personas con Discapacidad",
    "ACCESSIBILIDAD": "Ley General para la Inclusión de las Personas con Discapacidad",
    # Animales
    "LEY DE PROTECCION A LOS ANIMALES": "Ley Federal de Protección a la Animales",
    "PROTECCION A LOS ANIMALES": "Ley Federal de Protección a la Animales",
    "ANIMALES": "Ley Federal de Protección a la Animales",
    "BIENESTAR ANIMAL": "Ley Federal de Protección a la Animales",
    # Prevención de lavado de dinero
    "LEY ANTI LAVADO": "Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita",
    "PREVENCION DE LAVADO": "Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita",
    "LAVADO DE DINERO": "Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita",
    "OPERACIONES ILICITAS": "Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita",
    "RECURSOS ILICITOS": "Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita",
    # Planeación
    "LEY DE PLANEACION": "Ley de Planeación",
    "PLANEACION": "Ley de Planeación",
    "PLAN NACIONAL": "Ley de Planeación",
    # Archivos
    "LEY DE ARCHIVOS": "Ley Federal de Archivos",
    "ARCHIVOS": "Ley Federal de Archivos",
    "ARCHIVO": "Ley Federal de Archivos",
    # Otras leyes diversas
    "LEY DE CAZA": "Ley de Caza",
    "CAZA": "Ley de Caza",
    "LEY DE MONUMENTOS": "Ley Federal sobre Monumentos y Zonas Arqueológicos, Artísticos e Históricos",
    "MONUMENTOS": "Ley Federal sobre Monumentos y Zonas Arqueológicos, Artísticos e Históricos",
    "ARQUEOLOGICOS": "Ley Federal sobre Monumentos y Zonas Arqueológicos, Artísticos e Históricos",
    "ZONAS ARQUEOLOGICAS": "Ley Federal sobre Monumentos y Zonas Arqueológicos, Artísticos e Históricos",
    "LEY DEL IMPUESTO AUTOMOVIL": "Ley del Impuesto sobre Automóviles Nuevos",
    "IMPUESTO AUTOMOVIL": "Ley del Impuesto sobre Automóviles Nuevos",
    "AUTOMOVILES": "Ley del Impuesto sobre Automóviles Nuevos",
    "LEY DE BEBIDAS": "Ley Federal de Bebidas",
    "BEBIDAS": "Ley Federal de Bebidas",
    "ALCOHOL": "Ley Federal de Bebidas",
    "LEY DE RADICACION": "Ley de Radicación",
    "RADICACION": "Ley de Radicación",
    "LEY DE RESPONSABILIDADES": "Ley de Responsabilidades",
    "RESPONSABILIDADES": "Ley de Responsabilidades",
    "LEY DE SANEAMIENTO": "Ley de Saneamiento",
    "SANEAMIENTO": "Ley de Saneamiento",
    "LEY DE TESORERIA": "Ley de Tesorería",
    "TESORERIA": "Ley de Tesorería",
    "PROFECO": "Ley Orgánica de la Procuradoria Federal del Consumidor",
    "PROCURADURIA DEL CONSUMIDOR": "Ley Orgánica de la Procuradoria Federal del Consumidor",
    "CONSUMIDOR": "Ley Orgánica de la Procuradoria Federal del Consumidor",
    "LEY DE JUEGOS": "Ley Federal de Juegos y Sorteos",
    "JUEGOS Y SORTEOS": "Ley Federal de Juegos y Sorteos",
    "APUESTAS": "Ley Federal de Juegos y Sorteos",
    "SORTEOS": "Ley Federal de Juegos y Sorteos",
    "LEY ORGANICA DEL CONGRESO": "Ley Orgánica del Congreso General de los Estados Unidos Mexicanos",
    "CONGRESO": "Ley Orgánica del Congreso General de los Estados Unidos Mexicanos",
    "PRESUPUESTO": "Ley Federal de Presupuesto y Responsabilidad Hacendaria",
    "PRESUPUESTO Y RESPONSABILIDAD HACENDARIA": "Ley Federal de Presupuesto y Responsabilidad Hacendaria",
    "CODIGO FEDERAL DE INSTITUCIONES": "Código Federal de Instituciones y Procedimientos Electorales",
    "IFE": "Ley General de Instituciones y Procedimientos Electorales",
    "INSTITUTO FEDERAL ELECTORAL": "Ley General de Instituciones y Procedimientos Electorales",
    "IE": "Ley General de Instituciones y Procedimientos Electorales",
    "ELECTORAL": "Ley General de Instituciones y Procedimientos Electorales",
    "LEY DEL NOTARIADO": "Ley del Notariado",
    "NOTARIADO": "Ley del Notariado",
    "NOTARIO": "Ley del Notariado",
    "LEY DEL SEGURO": "Ley sobre el Contrato de Seguro",
    "CONTRATO DE SEGURO": "Ley sobre el Contrato de Seguro",
    "SEGURO": "Ley sobre el Contrato de Seguro",
    "PATRIMONIO CULTURAL": "Ley Federal de Protección del Patrimonio Cultural de los Pueblos y Comunidades Indígenas y Afromexicanas",
    "SALVAGUARDA DEL PATRIMONIO CULTURAL": "Ley Federal de Protección del Patrimonio Cultural de los Pueblos y Comunidades Indígenas y Afromexicanas",
    "LEY DE SEGURIDAD NACIONAL": "Ley de Seguridad Nacional",
    "SEGURIDAD NACIONAL": "Ley de Seguridad Nacional",
    # Fallbacks genéricos (menor prioridad)
    "CODIGO": "CÓDIGO CIVIL FEDERAL",
    "LEY": "Ley Federal del Trabajo",
}


SEMANTIC_KEYWORDS = [
    "explica",
    "relacion",
    "diferencia",
    "comparar",
    "ejemplo",
    "interpretación",
    "interpretar",
    "caso",
    "aplica",
    "aplicar",
    "porque",
    "por que",
    "porqué",
    "cómo",
    "como",
    "cuándo",
    "cuando",
    "qué establece",
    "que establece",
    "qué dice",
    "que dice",
    "define",
    "definición",
    "concepto",
    "significa",
    "requisitos",
    "condiciones",
    "procedimiento",
    "pasos",
    "ejemplos",
]


NUMBER_WORDS = {
    "uno": "1",
    "dos": "2",
    "tres": "3",
    "cuatro": "4",
    "cinco": "5",
    "seis": "6",
    "siete": "7",
    "ocho": "8",
    "nueve": "9",
    "diez": "10",
}
